import { ContributionData } from '../type/Calender.type';

export const contributionData: ContributionData[] = [
  // January 2023
  {
    day: '2023-01-03',
    value: 5,
    platform: 'github',
    details: '5 commits to portfolio project',
  },
  {
    day: '2023-01-05',
    value: 3,
    platform: 'leetcode',
    details: '3 medium difficulty problems solved',
  },
  {
    day: '2023-01-10',
    value: 8,
    platform: 'codeforces',
    details: '8 points earned in weekly contest',
  },
  {
    day: '2023-01-12',
    value: 2,
    platform: 'github',
    details: '2 commits to backend API',
  },
  {
    day: '2023-01-15',
    value: 4,
    platform: 'leetcode',
    details: '4 algorithm problems solved',
  },
  {
    day: '2023-01-19',
    value: 6,
    platform: 'other',
    details: '6 hours working on system design',
  },
  {
    day: '2023-01-22',
    value: 7,
    platform: 'github',
    details: '7 commits to UI components',
  },
  {
    day: '2023-01-28',
    value: 5,
    platform: 'codeforces',
    details: '5 points in div 2 contest',
  },

  // February 2023
  {
    day: '2023-02-01',
    value: 9,
    platform: 'github',
    details: '9 commits to authentication system',
  },
  {
    day: '2023-02-03',
    value: 2,
    platform: 'github',
    details: '2 commits to project setup',
  },
  {
    day: '2023-02-06',
    value: 3,
    platform: 'leetcode',
    details: '3 hard problems solved',
  },
  {
    day: '2023-02-07',
    value: 1,
    platform: 'github',
    details: '1 commit to fix critical bug',
  },
  {
    day: '2023-02-11',
    value: 4,
    platform: 'codeforces',
    details: '4 points in educational round',
  },
  {
    day: '2023-02-14',
    value: 7,
    platform: 'github',
    details: '7 commits to database migrations',
  },
  {
    day: '2023-02-18',
    value: 5,
    platform: 'other',
    details: '5 hours on cloud architecture',
  },
  {
    day: '2023-02-20',
    value: 6,
    platform: 'leetcode',
    details: '6 problems in weekly contest',
  },
  {
    day: '2023-02-23',
    value: 3,
    platform: 'leetcode',
    details: '3 binary search problems',
  },
  {
    day: '2023-02-25',
    value: 8,
    platform: 'github',
    details: '8 commits to API documentation',
  },

  // March 2023
  {
    day: '2023-03-02',
    value: 4,
    platform: 'codeforces',
    details: '4 points earned in div 3 round',
  },
  {
    day: '2023-03-05',
    value: 3,
    platform: 'leetcode',
    details: '3 linked list problems solved',
  },
  {
    day: '2023-03-07',
    value: 10,
    platform: 'github',
    details: '10 commits to deployment scripts',
  },
  {
    day: '2023-03-10',
    value: 2,
    platform: 'github',
    details: '2 commits to fix security vulnerabilities',
  },
  {
    day: '2023-03-12',
    value: 5,
    platform: 'leetcode',
    details: '5 problems solved in contest',
  },
  {
    day: '2023-03-15',
    value: 3,
    platform: 'other',
    details: '3 hours on microservices design',
  },
  {
    day: '2023-03-18',
    value: 4,
    platform: 'leetcode',
    details: '4 dynamic programming problems',
  },
  {
    day: '2023-03-21',
    value: 7,
    platform: 'github',
    details: '7 commits to frontend refactoring',
  },
  {
    day: '2023-03-24',
    value: 3,
    platform: 'codeforces',
    details: '3 points in div 3 round',
  },
  {
    day: '2023-03-27',
    value: 6,
    platform: 'codeforces',
    details: '6 points in div 2 competition',
  },
  {
    day: '2023-03-30',
    value: 5,
    platform: 'other',
    details: '5 hours on database optimization',
  },

  // April 2023
  {
    day: '2023-04-01',
    value: 2,
    platform: 'leetcode',
    details: '2 tree traversal problems',
  },
  {
    day: '2023-04-03',
    value: 8,
    platform: 'github',
    details: '8 commits to analytics dashboard',
  },
  {
    day: '2023-04-06',
    value: 3,
    platform: 'github',
    details: '3 commits to fix UI bugs',
  },
  {
    day: '2023-04-08',
    value: 4,
    platform: 'leetcode',
    details: '4 problems in biweekly contest',
  },
  {
    day: '2023-04-11',
    value: 2,
    platform: 'other',
    details: '2 hours on API design',
  },
  {
    day: '2023-04-14',
    value: 9,
    platform: 'codeforces',
    details: '9 points in global round',
  },
  {
    day: '2023-04-16',
    value: 4,
    platform: 'github',
    details: '4 commits to improve test coverage',
  },
  {
    day: '2023-04-18',
    value: 3,
    platform: 'other',
    details: '3 hours on CI/CD pipeline',
  },
  {
    day: '2023-04-20',
    value: 5,
    platform: 'leetcode',
    details: '5 graph problems solved',
  },
  {
    day: '2023-04-22',
    value: 7,
    platform: 'github',
    details: '7 commits to security patches',
  },
  {
    day: '2023-04-25',
    value: 3,
    platform: 'codeforces',
    details: '3 points in educational round',
  },
  {
    day: '2023-04-27',
    value: 5,
    platform: 'leetcode',
    details: '5 dynamic programming problems',
  },
  {
    day: '2023-04-30',
    value: 6,
    platform: 'github',
    details: '6 commits to feature implementation',
  },

  // May 2023
  {
    day: '2023-05-02',
    value: 6,
    platform: 'github',
    details: '6 commits to performance optimizations',
  },
  {
    day: '2023-05-04',
    value: 3,
    platform: 'leetcode',
    details: '3 string manipulation problems',
  },
  {
    day: '2023-05-06',
    value: 2,
    platform: 'codeforces',
    details: '2 points in div 3 contest',
  },
  {
    day: '2023-05-09',
    value: 8,
    platform: 'leetcode',
    details: '8 graph algorithm problems',
  },
  {
    day: '2023-05-12',
    value: 5,
    platform: 'github',
    details: '5 commits to code refactoring',
  },
  {
    day: '2023-05-14',
    value: 4,
    platform: 'codeforces',
    details: '4 points in educational round',
  },
  {
    day: '2023-05-16',
    value: 3,
    platform: 'leetcode',
    details: '3 array problems solved',
  },
  {
    day: '2023-05-18',
    value: 4,
    platform: 'github',
    details: '4 commits to UI enhancements',
  },
  {
    day: '2023-05-20',
    value: 7,
    platform: 'other',
    details: '7 hours on system architecture',
  },
  {
    day: '2023-05-22',
    value: 2,
    platform: 'leetcode',
    details: '2 linked list problems',
  },
  {
    day: '2023-05-25',
    value: 9,
    platform: 'github',
    details: '9 commits to testing suite',
  },
  {
    day: '2023-05-27',
    value: 3,
    platform: 'codeforces',
    details: '3 points in div 2 contest',
  },
  {
    day: '2023-05-31',
    value: 5,
    platform: 'leetcode',
    details: '5 binary tree problems solved',
  },

  // June 2023
  {
    day: '2023-06-01',
    value: 4,
    platform: 'github',
    details: '4 commits to dependency updates',
  },
  {
    day: '2023-06-03',
    value: 7,
    platform: 'leetcode',
    details: '7 problems in weekly contest',
  },
  {
    day: '2023-06-05',
    value: 2,
    platform: 'github',
    details: '2 commits to fix UI bugs',
  },
  {
    day: '2023-06-08',
    value: 6,
    platform: 'codeforces',
    details: '6 points in global round',
  },
  {
    day: '2023-06-10',
    value: 3,
    platform: 'other',
    details: '3 hours on database design',
  },
  {
    day: '2023-06-12',
    value: 5,
    platform: 'leetcode',
    details: '5 greedy algorithm problems',
  },
  {
    day: '2023-06-15',
    value: 8,
    platform: 'github',
    details: '8 commits to feature development',
  },
  {
    day: '2023-06-18',
    value: 4,
    platform: 'codeforces',
    details: '4 points in educational round',
  },
  {
    day: '2023-06-21',
    value: 6,
    platform: 'leetcode',
    details: '6 dynamic programming problems',
  },
  {
    day: '2023-06-24',
    value: 3,
    platform: 'github',
    details: '3 commits to code refactoring',
  },
  {
    day: '2023-06-27',
    value: 5,
    platform: 'other',
    details: '5 hours on microservices architecture',
  },
  {
    day: '2023-06-30',
    value: 7,
    platform: 'github',
    details: '7 commits to API implementation',
  },

  // July 2023
  {
    day: '2023-07-02',
    value: 5,
    platform: 'leetcode',
    details: '5 sorting algorithm problems',
  },
  {
    day: '2023-07-05',
    value: 8,
    platform: 'github',
    details: '8 commits to authentication system',
  },
  {
    day: '2023-07-08',
    value: 3,
    platform: 'codeforces',
    details: '3 points in div 2 round',
  },
  {
    day: '2023-07-10',
    value: 4,
    platform: 'leetcode',
    details: '4 tree traversal problems',
  },
  {
    day: '2023-07-13',
    value: 7,
    platform: 'github',
    details: '7 commits to frontend components',
  },
  {
    day: '2023-07-15',
    value: 2,
    platform: 'other',
    details: '2 hours on API documentation',
  },
  {
    day: '2023-07-18',
    value: 6,
    platform: 'leetcode',
    details: '6 problems in biweekly contest',
  },
  {
    day: '2023-07-21',
    value: 9,
    platform: 'github',
    details: '9 commits to testing framework',
  },
  {
    day: '2023-07-24',
    value: 4,
    platform: 'codeforces',
    details: '4 points in educational round',
  },
  {
    day: '2023-07-27',
    value: 3,
    platform: 'leetcode',
    details: '3 sliding window problems',
  },
  {
    day: '2023-07-30',
    value: 5,
    platform: 'other',
    details: '5 hours on system design',
  },

  // August 2023
  {
    day: '2023-08-01',
    value: 7,
    platform: 'github',
    details: '7 commits to API endpoints',
  },
  {
    day: '2023-08-04',
    value: 3,
    platform: 'leetcode',
    details: '3 backtracking problems',
  },
  {
    day: '2023-08-07',
    value: 5,
    platform: 'codeforces',
    details: '5 points in div 3 round',
  },
  {
    day: '2023-08-10',
    value: 8,
    platform: 'github',
    details: '8 commits to performance optimization',
  },
  {
    day: '2023-08-13',
    value: 4,
    platform: 'other',
    details: '4 hours on database optimization',
  },
  {
    day: '2023-08-15',
    value: 6,
    platform: 'leetcode',
    details: '6 heap problems solved',
  },
  {
    day: '2023-08-18',
    value: 3,
    platform: 'github',
    details: '3 commits to bugfixes',
  },
  {
    day: '2023-08-21',
    value: 7,
    platform: 'codeforces',
    details: '7 points in global round',
  },
  {
    day: '2023-08-24',
    value: 5,
    platform: 'leetcode',
    details: '5 graph traversal problems',
  },
  {
    day: '2023-08-27',
    value: 9,
    platform: 'github',
    details: '9 commits to UI/UX improvements',
  },
  {
    day: '2023-08-30',
    value: 4,
    platform: 'other',
    details: '4 hours on cloud infrastructure',
  },

  // September 2023
  {
    day: '2023-09-02',
    value: 6,
    platform: 'leetcode',
    details: '6 problems in weekly contest',
  },
  {
    day: '2023-09-05',
    value: 8,
    platform: 'github',
    details: '8 commits to deployment pipeline',
  },
  {
    day: '2023-09-08',
    value: 3,
    platform: 'codeforces',
    details: '3 points in educational round',
  },
  {
    day: '2023-09-11',
    value: 5,
    platform: 'leetcode',
    details: '5 dynamic programming problems',
  },
  {
    day: '2023-09-14',
    value: 7,
    platform: 'github',
    details: '7 commits to API integration',
  },
  {
    day: '2023-09-17',
    value: 2,
    platform: 'other',
    details: '2 hours on system architecture review',
  },
  {
    day: '2023-09-20',
    value: 4,
    platform: 'leetcode',
    details: '4 binary search problems',
  },
  {
    day: '2023-09-23',
    value: 9,
    platform: 'github',
    details: '9 commits to security enhancements',
  },
  {
    day: '2023-09-26',
    value: 5,
    platform: 'codeforces',
    details: '5 points in div 2 round',
  },
  {
    day: '2023-09-29',
    value: 3,
    platform: 'leetcode',
    details: '3 greedy algorithm problems',
  },

  // October 2023
  {
    day: '2023-10-01',
    value: 7,
    platform: 'github',
    details: '7 commits to feature implementation',
  },
  {
    day: '2023-10-04',
    value: 4,
    platform: 'leetcode',
    details: '4 array manipulation problems',
  },
  {
    day: '2023-10-07',
    value: 6,
    platform: 'codeforces',
    details: '6 points in global round',
  },
  {
    day: '2023-10-10',
    value: 8,
    platform: 'github',
    details: '8 commits to UI components',
  },
  {
    day: '2023-10-13',
    value: 3,
    platform: 'other',
    details: '3 hours on distributed systems',
  },
  {
    day: '2023-10-16',
    value: 5,
    platform: 'leetcode',
    details: '5 linked list problems',
  },
  {
    day: '2023-10-19',
    value: 9,
    platform: 'github',
    details: '9 commits to testing infrastructure',
  },
  {
    day: '2023-10-22',
    value: 4,
    platform: 'codeforces',
    details: '4 points in educational round',
  },
  {
    day: '2023-10-25',
    value: 7,
    platform: 'leetcode',
    details: '7 problems in biweekly contest',
  },
  {
    day: '2023-10-28',
    value: 5,
    platform: 'github',
    details: '5 commits to bug fixes',
  },
  {
    day: '2023-10-31',
    value: 6,
    platform: 'other',
    details: '6 hours on system design',
  },

  // November 2023
  {
    day: '2023-11-02',
    value: 8,
    platform: 'github',
    details: '8 commits to auth service',
  },
  {
    day: '2023-11-05',
    value: 3,
    platform: 'leetcode',
    details: '3 tree traversal problems',
  },
  {
    day: '2023-11-08',
    value: 5,
    platform: 'codeforces',
    details: '5 points in div 2 round',
  },
  {
    day: '2023-11-11',
    value: 7,
    platform: 'github',
    details: '7 commits to API endpoints',
  },
  {
    day: '2023-11-14',
    value: 4,
    platform: 'other',
    details: '4 hours on database schema design',
  },
  {
    day: '2023-11-17',
    value: 6,
    platform: 'leetcode',
    details: '6 dynamic programming problems',
  },
  {
    day: '2023-11-20',
    value: 9,
    platform: 'github',
    details: '9 commits to performance optimization',
  },
  {
    day: '2023-11-23',
    value: 3,
    platform: 'codeforces',
    details: '3 points in educational round',
  },
  {
    day: '2023-11-26',
    value: 5,
    platform: 'leetcode',
    details: '5 graph problems solved',
  },
  {
    day: '2023-11-29',
    value: 8,
    platform: 'github',
    details: '8 commits to deployment scripts',
  },

  // December 2023
  {
    day: '2023-12-02',
    value: 4,
    platform: 'leetcode',
    details: '4 sliding window problems',
  },
  {
    day: '2023-12-05',
    value: 7,
    platform: 'github',
    details: '7 commits to UI/UX improvements',
  },
  {
    day: '2023-12-08',
    value: 5,
    platform: 'codeforces',
    details: '5 points in global round',
  },
  {
    day: '2023-12-11',
    value: 3,
    platform: 'other',
    details: '3 hours on system architecture',
  },
  {
    day: '2023-12-14',
    value: 6,
    platform: 'leetcode',
    details: '6 backtracking problems',
  },
  {
    day: '2023-12-17',
    value: 8,
    platform: 'github',
    details: '8 commits to feature development',
  },
  {
    day: '2023-12-20',
    value: 4,
    platform: 'codeforces',
    details: '4 points in div 3 round',
  },
  {
    day: '2023-12-23',
    value: 7,
    platform: 'leetcode',
    details: '7 problems in weekly contest',
  },
  {
    day: '2023-12-26',
    value: 9,
    platform: 'github',
    details: '9 commits to end-of-year updates',
  },
  {
    day: '2023-12-29',
    value: 5,
    platform: 'other',
    details: '5 hours on code review',
  },

  // January 2024
  {
    day: '2024-01-02',
    value: 8,
    platform: 'github',
    details: '8 commits to new year project setup',
  },
  {
    day: '2024-01-05',
    value: 4,
    platform: 'leetcode',
    details: '4 array algorithm problems',
  },
  {
    day: '2024-01-08',
    value: 6,
    platform: 'codeforces',
    details: '6 points in educational round',
  },
  {
    day: '2024-01-11',
    value: 9,
    platform: 'github',
    details: '9 commits to database migrations',
  },
  {
    day: '2024-01-14',
    value: 3,
    platform: 'other',
    details: '3 hours on API documentation',
  },
  {
    day: '2024-01-17',
    value: 5,
    platform: 'leetcode',
    details: '5 tree problems solved',
  },
  {
    day: '2024-01-20',
    value: 7,
    platform: 'github',
    details: '7 commits to front-end components',
  },
  {
    day: '2024-01-23',
    value: 4,
    platform: 'codeforces',
    details: '4 points in div 2 round',
  },
  {
    day: '2024-01-26',
    value: 6,
    platform: 'leetcode',
    details: '6 dynamic programming problems',
  },
  {
    day: '2024-01-29',
    value: 8,
    platform: 'github',
    details: '8 commits to API implementation',
  },

  // February 2024
  {
    day: '2024-02-01',
    value: 5,
    platform: 'leetcode',
    details: '5 linked list problems',
  },
  {
    day: '2024-02-04',
    value: 9,
    platform: 'github',
    details: '9 commits to security features',
  },
  {
    day: '2024-02-07',
    value: 3,
    platform: 'codeforces',
    details: '3 points in global round',
  },
  {
    day: '2024-02-10',
    value: 7,
    platform: 'leetcode',
    details: '7 problems in biweekly contest',
  },
  {
    day: '2024-02-13',
    value: 4,
    platform: 'other',
    details: '4 hours on database optimization',
  },
  {
    day: '2024-02-16',
    value: 8,
    platform: 'github',
    details: '8 commits to UI/UX improvements',
  },
  {
    day: '2024-02-19',
    value: 5,
    platform: 'leetcode',
    details: '5 graph problems solved',
  },
  {
    day: '2024-02-22',
    value: 6,
    platform: 'codeforces',
    details: '6 points in educational round',
  },
  {
    day: '2024-02-25',
    value: 9,
    platform: 'github',
    details: '9 commits to refactoring',
  },
  {
    day: '2024-02-28',
    value: 3,
    platform: 'other',
    details: '3 hours on system design',
  },

  // March 2024
  {
    day: '2024-03-02',
    value: 7,
    platform: 'leetcode',
    details: '7 binary search problems',
  },
  {
    day: '2024-03-05',
    value: 8,
    platform: 'github',
    details: '8 commits to API optimization',
  },
  {
    day: '2024-03-08',
    value: 4,
    platform: 'codeforces',
    details: '4 points in div 3 round',
  },
  {
    day: '2024-03-11',
    value: 6,
    platform: 'leetcode',
    details: '6 tree traversal problems',
  },
  {
    day: '2024-03-14',
    value: 9,
    platform: 'github',
    details: '9 commits to testing suite',
  },
  {
    day: '2024-03-17',
    value: 3,
    platform: 'other',
    details: '3 hours on cloud infrastructure',
  },
  {
    day: '2024-03-20',
    value: 5,
    platform: 'leetcode',
    details: '5 dynamic programming problems',
  },
  {
    day: '2024-03-23',
    value: 7,
    platform: 'github',
    details: '7 commits to deployment automation',
  },
  {
    day: '2024-03-26',
    value: 4,
    platform: 'codeforces',
    details: '4 points in global round',
  },
  {
    day: '2024-03-29',
    value: 8,
    platform: 'leetcode',
    details: '8 problems in weekly contest',
  },

  // April 2024
  {
    day: '2024-04-01',
    value: 6,
    platform: 'github',
    details: '6 commits to feature integration',
  },
  {
    day: '2024-04-04',
    value: 3,
    platform: 'leetcode',
    details: '3 array manipulation problems',
  },
  {
    day: '2024-04-07',
    value: 5,
    platform: 'codeforces',
    details: '5 points in educational round',
  },
  {
    day: '2024-04-10',
    value: 9,
    platform: 'github',
    details: '9 commits to UI components',
  },
  {
    day: '2024-04-13',
    value: 4,
    platform: 'other',
    details: '4 hours on system architecture',
  },
  {
    day: '2024-04-16',
    value: 7,
    platform: 'leetcode',
    details: '7 graph traversal problems',
  },
  {
    day: '2024-04-19',
    value: 8,
    platform: 'github',
    details: '8 commits to backend services',
  },
  {
    day: '2024-04-22',
    value: 3,
    platform: 'codeforces',
    details: '3 points in div 2 round',
  },
  {
    day: '2024-04-25',
    value: 6,
    platform: 'leetcode',
    details: '6 problems in biweekly contest',
  },
  {
    day: '2024-04-28',
    value: 5,
    platform: 'github',
    details: '5 commits to bug fixes',
  },

  // May 2024
  {
    day: '2024-05-01',
    value: 7,
    platform: 'leetcode',
    details: '7 string algorithm problems',
  },
  {
    day: '2024-05-04',
    value: 9,
    platform: 'github',
    details: '9 commits to API endpoints',
  },
  {
    day: '2024-05-07',
    value: 4,
    platform: 'codeforces',
    details: '4 points in global round',
  },
  {
    day: '2024-05-10',
    value: 6,
    platform: 'leetcode',
    details: '6 dynamic programming problems',
  },
  {
    day: '2024-05-13',
    value: 8,
    platform: 'github',
    details: '8 commits to authentication system',
  },
  {
    day: '2024-05-16',
    value: 3,
    platform: 'other',
    details: '3 hours on database design',
  },
  {
    day: '2024-05-19',
    value: 5,
    platform: 'leetcode',
    details: '5 tree problems solved',
  },
  {
    day: '2024-05-22',
    value: 7,
    platform: 'github',
    details: '7 commits to code refactoring',
  },
  {
    day: '2024-05-25',
    value: 4,
    platform: 'codeforces',
    details: '4 points in educational round',
  },
  {
    day: '2024-05-28',
    value: 6,
    platform: 'leetcode',
    details: '6 heap problems solved',
  },
  {
    day: '2024-05-31',
    value: 9,
    platform: 'github',
    details: '9 commits to performance optimization',
  },

  // June 2024
  {
    day: '2024-06-03',
    value: 5,
    platform: 'leetcode',
    details: '5 graph problems solved',
  },
  {
    day: '2024-06-06',
    value: 8,
    platform: 'github',
    details: '8 commits to UI/UX improvements',
  },
  {
    day: '2024-06-09',
    value: 3,
    platform: 'codeforces',
    details: '3 points in div 3 round',
  },
  {
    day: '2024-06-12',
    value: 7,
    platform: 'leetcode',
    details: '7 problems in weekly contest',
  },
  {
    day: '2024-06-15',
    value: 4,
    platform: 'other',
    details: '4 hours on system design',
  },
  {
    day: '2024-06-18',
    value: 9,
    platform: 'github',
    details: '9 commits to API integration',
  },
  {
    day: '2024-06-21',
    value: 6,
    platform: 'leetcode',
    details: '6 dynamic programming problems',
  },
  {
    day: '2024-06-24',
    value: 5,
    platform: 'codeforces',
    details: '5 points in global round',
  },
  {
    day: '2024-06-27',
    value: 8,
    platform: 'github',
    details: '8 commits to feature development',
  },
  {
    day: '2024-06-30',
    value: 3,
    platform: 'other',
    details: '3 hours on microservices',
  },

  // July 2024
  {
    day: '2024-07-02',
    value: 7,
    platform: 'leetcode',
    details: '7 binary search problems',
  },
  {
    day: '2024-07-05',
    value: 9,
    platform: 'github',
    details: '9 commits to deployment scripts',
  },
  {
    day: '2024-07-08',
    value: 4,
    platform: 'codeforces',
    details: '4 points in educational round',
  },
  {
    day: '2024-07-11',
    value: 6,
    platform: 'leetcode',
    details: '6 linked list problems',
  },
  {
    day: '2024-07-14',
    value: 8,
    platform: 'github',
    details: '8 commits to backend services',
  },
  {
    day: '2024-07-17',
    value: 3,
    platform: 'other',
    details: '3 hours on API documentation',
  },
  {
    day: '2024-07-20',
    value: 5,
    platform: 'leetcode',
    details: '5 problems in biweekly contest',
  },
  {
    day: '2024-07-23',
    value: 7,
    platform: 'github',
    details: '7 commits to UI components',
  },
  {
    day: '2024-07-26',
    value: 4,
    platform: 'codeforces',
    details: '4 points in div 2 round',
  },
  {
    day: '2024-07-29',
    value: 6,
    platform: 'leetcode',
    details: '6 tree traversal problems',
  },

  // August 2024
  {
    day: '2024-08-01',
    value: 9,
    platform: 'github',
    details: '9 commits to feature implementation',
  },
  {
    day: '2024-08-04',
    value: 4,
    platform: 'leetcode',
    details: '4 dynamic programming problems',
  },
  {
    day: '2024-08-07',
    value: 5,
    platform: 'codeforces',
    details: '5 points in educational round',
  },
  {
    day: '2024-08-10',
    value: 7,
    platform: 'github',
    details: '7 commits to code refactoring',
  },
  {
    day: '2024-08-13',
    value: 3,
    platform: 'other',
    details: '3 hours on system architecture',
  },
  {
    day: '2024-08-15',
    value: 10,
    platform: 'github',
    details: '10 commits to open source project',
  },
  {
    day: '2024-08-18',
    value: 5,
    platform: 'leetcode',
    details: '5 graph problems solved',
  },
  {
    day: '2024-08-20',
    value: 6,
    platform: 'leetcode',
    details: '6 problems in weekly contest',
  },
  {
    day: '2024-08-23',
    value: 8,
    platform: 'github',
    details: '8 commits to testing framework',
  },
  {
    day: '2024-08-25',
    value: 8,
    platform: 'codeforces',
    details: '8 points in div 1 round',
  },
  {
    day: '2024-08-28',
    value: 4,
    platform: 'other',
    details: '4 hours on cloud deployment',
  },
  {
    day: '2024-08-31',
    value: 7,
    platform: 'github',
    details: '7 commits to API endpoints',
  },

  // September 2024
  {
    day: '2024-09-01',
    value: 7,
    platform: 'other',
    details: '7 hours on system design interview prep',
  },
  {
    day: '2024-09-03',
    value: 5,
    platform: 'leetcode',
    details: '5 binary tree problems',
  },
  {
    day: '2024-09-05',
    value: 9,
    platform: 'github',
    details: '9 commits to portfolio website',
  },
  {
    day: '2024-09-08',
    value: 4,
    platform: 'codeforces',
    details: '4 points in educational round',
  },
  {
    day: '2024-09-10',
    value: 5,
    platform: 'leetcode',
    details: '5 hard problems solved',
  },
  {
    day: '2024-09-13',
    value: 8,
    platform: 'github',
    details: '8 commits to authentication system',
  },
  {
    day: '2024-09-15',
    value: 6,
    platform: 'codeforces',
    details: '6 points in global round',
  },
  {
    day: '2024-09-17',
    value: 3,
    platform: 'leetcode',
    details: '3 string algorithm problems',
  },
  {
    day: '2024-09-20',
    value: 4,
    platform: 'other',
    details: '4 hours on distributed systems',
  },
  {
    day: '2024-09-23',
    value: 7,
    platform: 'github',
    details: '7 commits to feature development',
  },
  {
    day: '2024-09-26',
    value: 5,
    platform: 'leetcode',
    details: '5 problems in biweekly contest',
  },
  {
    day: '2024-09-29',
    value: 6,
    platform: 'codeforces',
    details: '6 points in div 2 round',
  },
  {
    day: '2025-09-30',
    value: 4,
    platform: 'other',
    details: '4 hours on code review',
  },
];
